### ISSUE TITLE
testing on openSUSE Tumbleweed fails

### ISSUE THREAD

**Issue by frispete** [jaraco/keyrings.alt#14]
in a non trivial way, at least for me:
```
_win_crypto (unittest.loader._FailedTest) ... ERROR
_win_crypto (unittest.loader._FailedTest) ... ERROR
[...]
======================================================================
ERROR: _win_crypto (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: _win_crypto
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/abuild/rpmbuild/BUILD/keyrings.alt-2.0/keyrings/alt/_win_crypto.py", line 4, in <module>
    from ctypes import windll, WinDLL, WINFUNCTYPE
ImportError: cannot import name 'windll'

======================================================================
ERROR: _win_crypto (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: _win_crypto
Traceback (most recent call last):
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/abuild/rpmbuild/BUILD/keyrings.alt-2.0/keyrings/alt/_win_crypto.py", line 4, in <module>
    from ctypes import windll, WinDLL, WINFUNCTYPE
ImportError: cannot import name 'windll'

----------------------------------------------------------------------
Ran 316 tests in 1.397s

FAILED (errors=2, skipped=112)
Test failed: <unittest.runner.TextTestResult run=316 errors=2 failures=0>
```

Why the hell does `unittest` attempt to load `_win_crypto` at all?

I'm building the `keyrings.alt` package besides a few [others](https://build.opensuse.org/project/monitor/home:frispete:python3) in preparation for the official `openSUSE` eco system [here](https://build.opensuse.org/package/show/home:frispete:python3/python3-keyrings.alt).
As you can see, this happens with Tumbleweed only (the rolling release version of openSUSE), that is based on `Python 3.5.1`, while the other targets run the tests just fine (all based on `Python 3.4.5`).

The full build log is available [here](https://build.opensuse.org/build/home:frispete:python3/openSUSE_Tumbleweed/x86_64/python3-keyrings.alt/_log)

@jaraco Sorry for bothering you with such things, but I'm lost with this one...

**Comment by jaraco** [comment]
I'm not able to read the build log, but when I run tests on macOS and Ubuntu (such as is regularly [done with Travis](https://travis-ci.org/jaraco/keyrings.alt)), the tests pass just fine. There is a directive in `conftest.py` to ignore the collection of that file. Looks like you're running the tests using unittest rather than tox/pytest, which is the recommended and only supported test runner for this project.
